services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/backend-app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/frontend-app
      - /frontend-app/node_modules
    stdin_open: true
    tty: true
