services:
  backend:
    build:
      context: ./backend
    image: joshkeisler.au@gmail.com/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    image: joshkeisler.au@gmail.com/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15.4-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
