version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Map the container's port to the host's port
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python outputs logs to console in real-time
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3000:3000"  # Map the container's port to the host's port
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
