services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/joshkeisler_cert.crt:/etc/ssl/certs/joshkeisler_cert.crt:ro
      - /etc/ssl/private/joshkeisler_key.key:/etc/ssl/private/joshkeisler_key.key:ro
    depends_on:
      - backend
      - frontend

  backend:
    build:
      target: production

  frontend:
    build:
      target: production
