# Generated by Django 5.1.2 on 2024-10-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="page_reference",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
