# Generated by Django 5.1.2 on 2024-10-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("descriptions", "0002_description_page_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="description",
            old_name="page_reference",
            new_name="page",
        ),
    ]
