# Generated by Django 5.1.2 on 2024-11-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descriptions", "0003_rename_page_reference_description_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="page",
            field=models.CharField(max_length=255),
        ),
    ]
