# Generated by Django 5.1.2 on 2024-11-26 21:33

from django.db import migrations


def update_page_field(apps, schema_editor):
    Description = apps.get_model("descriptions", "Description")
    for description in Description.objects.filter(page="2"):
        description.page = "psychology"
        description.save()


class Migration(migrations.Migration):

    dependencies = [
        ("descriptions", "0004_alter_description_page"),
    ]

    operations = [
        migrations.RunPython(update_page_field),
    ]
