name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Development Images
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > backend/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/.env
          echo "HOST_USER_EMAIL=${{ secrets.HOST_USER_EMAIL }}" >> backend/.env
          docker compose build

      - name: Run Backend Tests
        run: docker compose run backend python manage.py test

      - name: Run Frontend Tests
        run: docker compose run frontend npm test -- --silent --watchAll=false

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no linuxuser@${{secrets.VULTR_IP_ADDRESS }} << 'EOF'
            cd ~/web-resume

            git pull origin main

            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > backend/.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/.env
            echo "HOST_USER_EMAIL=${{ secrets.HOST_USER_EMAIL }}" >> backend/.env
            echo "MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }}" >> backend/.env
            echo "MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}" >> backend/.env
            docker-compose -f compose.yaml -f production.yaml up --build -d

            docker system prune -af
            docker volume prune -f
          EOF
